# fly.toml app configuration file generated for pingloibot on 2023-09-23T15:26:41+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pingloibot"
primary_region = "sin"

[build]
