# fly.toml app configuration file generated for pingloi on 2023-09-10T21:49:36+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pingloi"
primary_region = "sin"

[build]
